#!/bin/bash
INPUT=
SAM=
FASTA=
USAGE="Usage: ace2sam.sh -i <in.ace> -f <out.fa> -s <out.sam>"
while getopts ":i:hf:s:" opt; do
    case $opt in
        i)
           INPUT=$OPTARG
            ;;
        f)
            FASTA=$OPTARG
            ;;
        s)
            SAM=$OPTARG
            ;;
        h)
            echo $USAGE
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ -z "$INPUT" ] || [ -z "$FASTA" ] || [ -z "$SAM" ]
then
echo $USAGE

else

OUT_FILE="/tmp/$(basename $0).$RANDOM.txt"
ERR_FILE="/tmp/$(basename $0).$RANDOM.txt"

ace2sam_bin $INPUT >$OUT_FILE 2>$ERR_FILE && (grep ^H $ERR_FILE | sed s,^..,,; cat $OUT_FILE) > $SAM && grep ^S $ERR_FILE | sed s,^..,, > $FASTA && rm $OUT_FILE $ERR_FILE

# Report errors if there were errors
if [ -f $ERR_FILE ];
then
    cat $ERR_FILE
fi

fi


