#!/bin/bash
INPUT=
SAM=
FASTA=
USAGE="Usage: ace2sam.sh -i <in.ace> -f <out.fa> -s <out.sam>"
while getopts ":i:hf:s:" opt; do
    case $opt in
        i)
           INPUT=$OPTARG
            ;;
        f)
            FASTA=$OPTARG
            ;;
        s)
            SAM=$OPTARG
            ;;
        h)
            echo $USAGE
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ -z "$INPUT" ] || [ -z "$FASTA" ] || [ -z "$SAM" ]
then
echo $USAGE

else
ace2sam_bin $INPUT >a2s.out 2>a2s.err && (grep ^H a2s.err | sed s,^..,,; cat a2s.out) > $SAM && grep ^S a2s.err | sed s,^..,, > $FASTA && rm a2s.out a2s.err

# Report errors if there were errors
if [ -f a2s.err ];
then
    cat a2s.err
fi

fi


